# -*- coding: utf-8 -*-
"""DataScienceLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxRhBZGx7KqLo3vgMTE1Kt4Kxy0GLxiN
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
from src.model import CNNModel



datasets.MNIST.mirrors = ["https://ossci-datasets.s3.amazonaws.com/mnist/"]

transform = transforms.ToTensor()

# 2. Download and load the training and testing datasets
train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

# 3. Create DataLoaders to handle batching (processing 64 images at a time)
train_loader = DataLoader(dataset=train_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(dataset=test_dataset, batch_size=64, shuffle=False)

print(f"Training batches: {len(train_loader)}")
print(f"Testing batches: {len(test_loader)}")

# 1. Get a single batch of images and labels
dataiter = iter(train_loader)
images, labels = next(dataiter)

# 2. Visualize the first 5 images in this batch
plt.figure(figsize=(10, 2))
for i in range(5):
    plt.subplot(1, 5, i + 1)
    # images[i].squeeze() converts shape from (1, 28, 28) to (28, 28)
    plt.imshow(images[i].squeeze(), cmap='gray')
    plt.title(f"Label: {labels[i].item()}")
    plt.axis('off')
plt.tight_layout()
plt.show()


# Instantiate the model
model = CNNModel()
print(model)

# 1. Loss function: Cross Entropy is standard for multi-class classification
criterion = nn.CrossEntropyLoss()

# 2. Optimizer: Adam is fast and reliable. We tell it to update our model's parameters
optimizer = optim.Adam(model.parameters(), lr=0.001)

from tqdm import tqdm

epochs = 5
epoch_losses = []

print("Starting training...")

for epoch in range(epochs):
    running_loss = 0.0

    progress_bar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{epochs}', leave=False)

    for images, labels in progress_bar:
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        progress_bar.set_postfix({'loss': f'{loss.item():.4f}'})

    # Calculate average loss for this entire epoch
    avg_loss = running_loss / len(train_loader)
    epoch_losses.append(avg_loss)

    # Print a clean summary string after the progress bar clears
    print(f"Epoch [{epoch+1}/{epochs}] Completed - Average Loss: {avg_loss:.4f}")

print("Training Complete!")

# Plot the training loss curve
plt.figure(figsize=(8, 5))
plt.plot(range(1, epochs + 1), epoch_losses, marker='o', linestyle='-', color='b', linewidth=2)

plt.title('Model Training Progress (Learning Curve)')
plt.xlabel('Epoch (Number of passes through the dataset)')
plt.ylabel('Average Loss (Error)')
plt.xticks(range(1, epochs + 1))
plt.grid(True, linestyle='--', alpha=0.7)

plt.show()

model.eval()

correct = 0
total = 0

# 2. Turn off gradient tracking to save memory and speed up computation
with torch.no_grad():
    for images, labels in test_loader:
        outputs = model(images)
        # Get the index of the highest prediction
        _, predicted = torch.max(outputs.data, 1)

        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f"\nFinal Test Accuracy: {(100 * correct / total):.2f}%")

# 3. Visualize a few predictions from the test set
dataiter = iter(test_loader)
images, labels = next(dataiter)
outputs = model(images)
_, predicted = torch.max(outputs, 1)

plt.figure(figsize=(10, 3))
for i in range(5):
    plt.subplot(1, 5, i + 1)
    plt.imshow(images[i].squeeze(), cmap='gray')

    # Format the title text
    color = 'green' if predicted[i].item() == labels[i].item() else 'red'
    plt.title(f"Pred: {predicted[i].item()}\nTrue: {labels[i].item()}", color=color)
    plt.axis('off')

plt.tight_layout()
plt.show()

import torch

# 1. Define the file name (must match what the Streamlit app expects)
model_save_path = 'mnist_cnn_model.pth'

# 2. Save the model's learned weights (the state_dict)
torch.save(model.state_dict(), model_save_path)

print(f"✅ Model weights successfully saved to: {model_save_path}")
print("You can now use this file for your Streamlit web deployment!")

import os
from torchvision import datasets
from PIL import Image

folder_name = 'mnist_sample_images'
os.makedirs(folder_name, exist_ok=True)

test_dataset = datasets.MNIST(root='./data', train=False, download=True)

saved_digits = set()
idx = 0

print("Extracting images...")

while len(saved_digits) < 10 and idx < len(test_dataset):
    image, label = test_dataset[idx]

    if label not in saved_digits:
        file_path = os.path.join(folder_name, f"actual_digit_{label}.png")
        image.save(file_path)
        saved_digits.add(label)
        print(f"✅ Saved a '{label}' to {file_path}")

    idx += 1

print("\nDone! Check the 'mnist_sample_images' folder.")